# Coopetition of Danish banks

This notebook contains econometric models exploring usage of shared IT providers among Danish banks.

## Step 1. Load KPI spreadsheet from Finanstilsynet

In [4]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# PI_D is a hidden sheet that contains the data for pivot tables PI_A & PI_B
kpis = (pd.read_excel(io="data/KPI_Penge_fonds_Real_202412.xlsx", sheet_name="PI_D")
        .rename(columns={"vaerdi": "value",
                   "År (Year)": "year",
                   "Vælg nøgletal (Choose KPI)": "kpi",
                   "Virksomhedsnavn (Company Name)": "bank"
                   })
        .dropna(subset=["value"])
        .assign(year=lambda x: x["year"].astype(int)))
kpis.drop(columns=["Vælg niveau (Choose Company Level)",
                 "Vælg virksomhedsgruppering (Choose Company Grouping)",
                 "ITYPE"], inplace=True)
kpi_map = {
    "Solvensprocent (Solvency ratio)": "solvency_ratio",
    "Kernekapitalprocent (Tier 1 capital ratio)": "tier1_cap",
    "Egenkapitalforrentning før skat (Return on equity before tax)": "roe_pre_tax",
    "Egenkapitalforrentning efter skat (Return on equity after tax)": "roe_post_tax",
    "Indtjening pr. omkostningskrone (Income/cost ratio)": "income_to_cost",
    "Renterisiko (Interest rate risk)": "interest_rate_risk",
    "Valutaposition (Foreign exchange position)": "fx_position",
    "Valutarisiko (Foreign exchange risk)": "fx_risk",
    "Udlån plus nedskrivninger herpå i forhold til indlån (Loans and impairment losses over deposits)": "loans_over_deposits",
    "Overdækning i forhold til lovkrav om likviditet (Excess coverage as a percentage of the liquidity requirement)": "liq_coverage",
    "Summen af store eksponeringer (Sum of large exposures)": "large_exposures",
    "Årets nedskrivningsprocent (Annual impairment ratio)": "impairment_ratio",
    "Årets udlånsvækst (Growth in loans)": "loan_growth",
    "Udlån i forhold til egenkapital (Gearing)": "gearing",
    "Årets resultat pr. aktie (stykstørrelse 100 kr.) (Annual earnings per share (nominal value DKK 100) before tax)": "eps_pre_tax",
    "Årets resultat pr. aktie (stykstørrelse 100 kr.) (Annual earnings per share (nominal value DKK 100) after tax)": "eps_post_tax",
    "Indre værdi pr. aktie (stykstørrelse 100 kr.)(Book value over net asset value)": "book_value_per_share",
    "Børskurs/resultat pr. aktie (stykstørrelse 100 kr.) (Price over net asset value (nominal value DKK 100))": "price_over_nav",
    "Børskurs/indre værdi pr. aktie (stykstørrelse 100 kr.) (Price over book value (nominal value DKK100))": "price_over_book"
}
kpis["kpi"] = kpis["kpi"].map(kpi_map)


## Step 2. Add datacentral information

In [5]:
platforms = pd.read_excel("data/BankByDC.xlsx")
kpis_platforms = kpis.merge(platforms, on="bank", how="left")
# some banks are missing datacentral information - those are not interesting for further analysis
kpis_platforms = kpis_platforms.dropna(subset=["dc"])

## Step 3. From long to wide format
REGNR is one of ids for the banks.

In [6]:
df_wide = kpis_platforms.pivot_table(index=["bank", "year", "dc", "REGNR"], columns="kpi", values="value").reset_index()

## Step 4. Add balance sheet data
PI_regnskaber_2000_2024.xlsx is another spreadsheet from Finanstilsynet that contains balance sheets for the banks. Due to the change in reporting forms across the years, getting the data requires more effort here. We will be using the following metrics:
* Total assets (*Aktiver i alt*), coded as FB0214, AS0222 and Bal_BO_ATot
* Income from fees and commissions (*Gebyrer og provisionsindtægter*), coded as FB0105, AS0105 and Res_GPi_RY
* Income from interest and fees (=total income) (*Netto rente- og gebyrindtægter*), coded as FB0107, AS0107 and Res_RGTot_RY
* Deposits: coded as *Indlån* FB0216 and summed from *Indlån og anden gæld* (AS0224, Bal_BO_PGiag) and *Indlån i puljeordninger* (AS0225, Bal_BO_Pgip)
* Loans: coded as *Udlån* FB0204 and summed from *Udlån og andre tilgodehavender til dagsværdi* (AS0204, Bal_BO_Autd) and *Udlån og andre tilgodehavender til amortiseret kostpris* (AS0205, Bal_BO_Auta)

Total assets are later logarithmized.

Deposits and loans are later expressed as ratio of total assets (as in Dreyer (2018)).

To verify if the bank is more traditional (more income from interest) or digital (income from services), we calculate a third variable which is the percentage of non-interest income.

In [7]:
# Data_FB is a sheet that contains data for 2000-2004 period
balance_00_04 = pd.read_excel(io="data/PI_regnskaber_2000_2024.xlsx", sheet_name="Data_FB")
balance_00_04["year"] = balance_00_04["REGNPER"] // 100
balance_00_04.rename(columns={"FB0214": "total_assets",
                              "FB0105": "fee_commission_income",
                              "FB0107": "total_income",
                              "FB0216": "deposits",
                              "FB0204": "loans",
                              "FB0110": "admin_expenses"},
                     inplace=True)

# Data_AS is a sheet that contains data for 2005-2015 period
balance_05_15 = pd.read_excel(io="data/PI_regnskaber_2000_2024.xlsx", sheet_name="Data_AS")
balance_05_15["year"] = balance_05_15["REGNPER"] // 100
balance_05_15.rename(columns={"AS0222": "total_assets",
                              "AS0105": "fee_commission_income",
                              "AS0107": "total_income",
                              "AS0224": "deposits_other",
                              "AS0225": "pooled_deposits",
                              "AS0204": "loans_fv",
                              "AS0205": "loans_ac",
                              "AS0110": "admin_expenses"},
                     inplace=True)
balance_05_15["deposits"] = balance_05_15["deposits_other"].add(balance_05_15["pooled_deposits"], fill_value=0)
balance_05_15["loans"] = balance_05_15["loans_fv"].add(balance_05_15["loans_ac"], fill_value=0)

# Data_KRGS is a sheet that contains data for 2016-2024 period
balance_16_24 = pd.read_excel(io="data/PI_regnskaber_2000_2024.xlsx", sheet_name="Data_KRGS")
balance_16_24["year"] = balance_16_24["ref_date"] // 100
balance_16_24.rename(columns={"regnr": "REGNR",
                              "Bal_BO_ATot": "total_assets",
                              "Res_GPi_RY": "fee_commission_income",
                              "Res_RGTot_RY": "total_income",
                              "Bal_BO_PGiag": "deposits_other",
                              "Bal_BO_PGip": "pooled_deposits",
                              "Bal_BO_Autd": "loans_fv",
                              "Bal_BO_Auta": "loans_ac",
                              "Res_UPa_RY": "admin_expenses"},
                     inplace=True)
balance_16_24["deposits"] = balance_16_24["deposits_other"].add(balance_16_24["pooled_deposits"], fill_value=0)
balance_16_24["loans"] = balance_16_24["loans_fv"].add(balance_16_24["loans_ac"], fill_value=0)

balance_all = pd.concat(
    [balance_00_04, balance_05_15, balance_16_24],
    ignore_index=True
)

df_wide_balance = df_wide.merge(
    balance_all[["REGNR", "total_assets", "year", "fee_commission_income", "total_income", "deposits", "loans", "admin_expenses"]],
    on=["REGNR", "year"],
    how="left"
)

df_wide_balance["log_total_assets"] = np.log(df_wide_balance["total_assets"])
df_wide_balance["non_interest_income"] = df_wide_balance["fee_commission_income"] / df_wide_balance["total_income"]
df_wide_balance["deposits_over_assets"] = df_wide_balance["deposits"] / df_wide_balance["total_assets"]
df_wide_balance["loans_over_assets"] = df_wide_balance["loans"] / df_wide_balance["total_assets"]
df_wide_balance["admin_exp_over_assets"] = df_wide_balance["admin_expenses"] / df_wide_balance["total_assets"]


## Step 6. Dummies for DCs
Banks can be on one of three datacentrals: BEC, Netcompany Banking Services (NBS) or Bankdata. They can also build/buy IT solutions on their own (mainly Danske Bank and Nordea).

In [8]:
df_dummies = df_wide_balance.copy()
df_dummies["dc"] = pd.Categorical(
    df_dummies["dc"],
    categories=["OWN", "BEC", "NBS", "Bankdata"],
    ordered=True
)
df_dummies = pd.get_dummies(df_dummies, columns=["dc"], drop_first=False, dtype=int)


## Step 7. Basic data analysis

The panel is unbalanced, mostly because of banks merging over the years.

Based on Dreyer (2018) and our own experience, we pick the following variables from our dataset:

* income_to_cost (dependent variable)
* dc_BEC (dummy for datacentral)
* dc_NBS (dummy for datacentral)
* dc_Bankdata (dummy for datacentral)
* log_total_assets (as in Dreyer (2018))
* tier1_cap (as in Dreyer (2018))
* deposits_over_assets (as in Dreyer (2018))
* loans_over_assets (as in Dreyer (2018))
* non_interest_income (as in Dreyer (2018))
* gearing (as in Dreyer (2018), where it is called leverage ratio)

Let's check the quality of those.


In [9]:
df_short = df_dummies[["income_to_cost", "dc_NBS", "dc_Bankdata", "log_total_assets", "tier1_cap", "deposits_over_assets", "loans_over_assets", "non_interest_income", "gearing", "year", "bank", "fee_commission_income", "admin_exp_over_assets", "dc_BEC", "dc_OWN"]].copy()
for col in df_short:
    pct_missing = np.mean(df_short[col].isnull())
    print(col, '\t', pct_missing * 100, '%')

income_to_cost 	 0.0 %
dc_NBS 	 0.0 %
dc_Bankdata 	 0.0 %
log_total_assets 	 0.0 %
tier1_cap 	 0.0 %
deposits_over_assets 	 0.0 %
loans_over_assets 	 0.0 %
non_interest_income 	 0.0 %
gearing 	 0.20394289598912305 %
year 	 0.0 %
bank 	 0.0 %
fee_commission_income 	 0.0 %
admin_exp_over_assets 	 0.0 %
dc_BEC 	 0.0 %
dc_OWN 	 0.0 %


In [10]:
# basic cleaning - drop NaN rows
df_clean = df_short.dropna()

In [11]:

# Lag on data - in Dreyer (2018) they use all variables lagged by a year

lag_vars = [
   "log_total_assets", "tier1_cap",
    "deposits_over_assets", "loans_over_assets",
    "non_interest_income", "gearing", "fee_commission_income",
    "income_to_cost", "admin_exp_over_assets"
]

df_clean = (
    df_clean
    .set_index(["bank", "year"])
    .sort_index()
    .copy()
)

for v in lag_vars:
    df_clean[v + "_lag"] = df_clean.groupby(level=0)[v].shift(1)

df_clean = df_clean.dropna();

In [12]:
# Winsor
from scipy.stats.mstats import winsorize
df_clean = df_clean.copy()
cols_to_winsorize = [
    "log_total_assets_lag",
    "tier1_cap_lag",
    "deposits_over_assets_lag",
    "loans_over_assets_lag",
    "non_interest_income_lag",
    "gearing_lag",
    "fee_commission_income_lag",
    "income_to_cost_lag",
    "admin_exp_over_assets_lag",
    "income_to_cost"
]

for col in cols_to_winsorize:
    if col in df_clean.columns:
        df_clean[col] = winsorize(df_clean[col], limits=[0.01, 0.01])


Statistics of the data:

In [13]:

def get_panel_stats(df, column, entity_col='bank'):
    # overall
    overall_mean = df[column].mean()
    overall_std = df[column].std()
    overall_min = df[column].min()
    overall_max = df[column].max()
    n_obs = df[column].count()

    # between (the banks)
    between_means = df.groupby(entity_col)[column].mean()
    between_std = between_means.std()
    between_min = between_means.min()
    between_max = between_means.max()
    n_entities = between_means.count()

    # within (a bank over time)
    # subtract group mean, add overall mean (so the scale remains the same)
    within_data = df[column] - df.groupby(entity_col)[column].transform('mean') + overall_mean
    within_std = within_data.std()
    within_min = within_data.min()
    within_max = within_data.max()

    stats = pd.DataFrame({
        'Statistic': ['Overall', 'Between', 'Within'],
        'Mean': [overall_mean, overall_mean, overall_mean],
        'Std. Dev.': [overall_std, between_std, within_std],
        'Min': [overall_min, between_min, within_min],
        'Max': [overall_max, between_max, within_max],
        'Observations': [n_obs, n_entities, f"T-avg: {n_obs/n_entities:.1f}"]
    })

    return stats

df_c = df_clean.query("year >= 2015").copy()
variables = ['income_to_cost', "dc_BEC", "dc_NBS", "dc_Bankdata", "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag", "non_interest_income_lag", "gearing_lag"]
for var in variables:
    print(f"\nStats for {var}:")
    print(get_panel_stats(df_c, var))


Stats for income_to_cost:
  Statistic      Mean  Std. Dev.       Min       Max Observations
0   Overall  1.431418   0.463692  0.140000  3.440000          486
1   Between  1.431418   0.408084  0.260000  2.759000           58
2    Within  1.431418   0.271286  0.571418  2.647418   T-avg: 8.4

Stats for dc_BEC:
  Statistic      Mean     Std. Dev.       Min       Max Observations
0   Overall  0.393004  4.889210e-01  0.000000  1.000000          486
1   Between  0.393004  4.968138e-01  0.000000  1.000000           58
2    Within  0.393004  1.111367e-16  0.393004  0.393004   T-avg: 8.4

Stats for dc_NBS:
  Statistic     Mean     Std. Dev.      Min      Max Observations
0   Overall  0.36214  4.811142e-01  0.00000  1.00000          486
1   Between  0.36214  4.734321e-01  0.00000  1.00000           58
2    Within  0.36214  5.556835e-17  0.36214  0.36214   T-avg: 8.4

Stats for dc_Bankdata:
  Statistic     Mean     Std. Dev.      Min      Max Observations
0   Overall  0.17284  3.784981e-01  0.000

## Step 8. Simple model
income-to-cost on various DCs in 2024

In [ ]:
# let's focus only on 2024
df = df_clean.xs(2024, level="year").copy()

y = df["income_to_cost"]
X = df.drop(columns=["dc_OWN"])[["dc_NBS", "dc_Bankdata", "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag", "non_interest_income_lag", "gearing_lag"]]
X = sm.add_constant(X)

# Used robust standard errors (HC3) to account for heteroskedasticity
model = sm.OLS(y, X).fit(cov_type='HC3')
print(model.summary())


We're surprised by relatively high R<sup>2</sup> given the low number of samples (44). All variables are statistically nonsignificant.

High multicollinearity.

We need to make a panel analysis.

## Step 9. PooledOLS
In PooledOLS we assume that each bank in each year is a new observation.

In [15]:
from linearmodels.panel import PooledOLS

df = df_clean.query("year >= 2015").copy()

y = df["income_to_cost"]
#X = df.drop(columns=["dc_OWN"])[["dc_NBS", "dc_Bankdata", "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag", "non_interest_income_lag", "gearing_lag"]]
X = df[["dc_BEC", "dc_NBS", "dc_Bankdata", "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag", "non_interest_income_lag", "gearing_lag"]]
X = sm.add_constant(X)

pooled_mod = PooledOLS(y, X)
pooled_res = pooled_mod.fit(cov_type="clustered", cluster_entity=True)

print(pooled_res.summary)

                          PooledOLS Estimation Summary                          
Dep. Variable:         income_to_cost   R-squared:                        0.3303
Estimator:                  PooledOLS   R-squared (Between):              0.4964
No. Observations:                 486   R-squared (Within):               0.0329
Date:                Thu, May 28 2026   R-squared (Overall):              0.3303
Time:                        00:39:03   Log-likelihood                   -218.18
Cov. Estimator:             Clustered                                           
                                        F-statistic:                      26.081
Entities:                          58   P-value                           0.0000
Avg Obs:                       8.3793   Distribution:                   F(9,476)
Min Obs:                       1.0000                                           
Max Obs:                      10.0000   F-statistic (robust):             6.1650
                            

The model is statistically significant. R<sup>2</sup> rather low, but it is expected in panel. R<sup>2</sup> between = 0.4964: pretty well explains the differences between the banks, and pretty bad changes in time for the bank (R<sup>2</sup> within =0.0329).

The variables are mostly significant and make sense!

But, in general, the finances of the bank explain cost/income better than IT supplier.

# Fixed effects

Among Danish banks, the selection of DC is rather constant. Changes happen rarely and are mostly effects of bank mergers. The data was prepared on purpose to have constant DC decisions (e.g. Spar Nord switched from SDC to BEC in 2014 and that was the last main switch, thus we only use the data after 2015).
That's why Fixed effects is not helpful to answer the research questions, because dummies will be removed. But we calculate it anyway, so we can compare it with Random Effects later when it comes to time-relative variables.

In [37]:
from linearmodels.panel import PanelOLS

X_fe = df[["log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag", "non_interest_income_lag", "gearing_lag"]]

fe_mod = PanelOLS(y, X_fe, entity_effects=True)
#fe_res = fe_mod.fit()
fe_res = fe_mod.fit(cov_type="clustered", cluster_entity=True)

print(fe_res.summary)

                          PanelOLS Estimation Summary                           
Dep. Variable:         income_to_cost   R-squared:                        0.1687
Estimator:                   PanelOLS   R-squared (Between):             -5.2703
No. Observations:                 486   R-squared (Within):               0.1687
Date:                Thu, May 28 2026   R-squared (Overall):             -4.5603
Time:                        01:04:05   Log-likelihood                   -10.183
Cov. Estimator:             Clustered                                           
                                        F-statistic:                      14.272
Entities:                          58   P-value                           0.0000
Avg Obs:                       8.3793   Distribution:                   F(6,422)
Min Obs:                       1.0000                                           
Max Obs:                      10.0000   F-statistic (robust):             9.4389
                            

## Random effects.

We cannot use Fixed Effects, because the selection of DC is rather constant (changes happen rarely and are mostly effects of bank mergers).



In [38]:
from linearmodels.panel import RandomEffects


re_mod = RandomEffects(y, X)
#re_res = re_mod.fit()
re_res = re_mod.fit(cov_type="clustered", cluster_entity=True)

print(re_res.summary)

                        RandomEffects Estimation Summary                        
Dep. Variable:         income_to_cost   R-squared:                        0.1304
Estimator:              RandomEffects   R-squared (Between):              0.3516
No. Observations:                 486   R-squared (Within):               0.1062
Date:                Thu, May 28 2026   R-squared (Overall):              0.2647
Time:                        01:04:07   Log-likelihood                   -62.460
Cov. Estimator:             Clustered                                           
                                        F-statistic:                      7.9322
Entities:                          58   P-value                           0.0000
Avg Obs:                       8.3793   Distribution:                   F(9,476)
Min Obs:                       1.0000                                           
Max Obs:                      10.0000   F-statistic (robust):             10.100
                            

In [39]:
import numpy as np

# Breusch-Pagam LM test
resids = pooled_res.resids
n = df.index.get_level_values(0).nunique()
t = df.index.get_level_values(1).nunique()

grouped_resids = resids.groupby(level=0).sum()
lm_stat = (n * t / (2 * (t - 1))) * ( (np.sum(grouped_resids**2) / np.sum(resids**2)) - 1 )**2

from scipy.stats import chi2
p_value = 1 - chi2.cdf(lm_stat, 1)

print(f"LM stat: {lm_stat}")
print(f"P-value: {p_value}")

LM stat: 346.7556523004904
P-value: 0.0


We cannot use PooledOLS.

# Hausman test

## Important! Turn the clustering off for FE and RE before the test. (commented out lines)
The covariance matrix with clustering (or the diff to be precise) may not be positive.
But turining the clustering off for the test and then turning it on again does NOT change the interpretation of the results.

In [36]:
import numpy as np
import scipy.stats as stats

vars_to_compare = X_fe.columns.tolist()

# 2. b coeff. and cov matrices
b_fe = fe_res.params[vars_to_compare]
b_re = re_res.params[vars_to_compare]
v_fe = fe_res.cov.loc[vars_to_compare, vars_to_compare]
v_re = re_res.cov.loc[vars_to_compare, vars_to_compare]

# Hausman stat
diff = b_fe - b_re
precision = np.linalg.inv(v_fe - v_re)
stat = diff.T @ precision @ diff

# p-value
df_deg = len(vars_to_compare)
p_val = stats.chi2.sf(stat, df_deg)

print(f"Hausman stat: {stat:.4f}")
print(f"P-value: {p_val:.4f}")

Hausman stat: 37.0846
P-value: 0.0000


p-value < 0.05. Our RE model is biased, we should use FE.

In [40]:
# Model compare
from linearmodels.panel import compare
compare({'PooledOLS': pooled_res, 'RE': re_res, 'FE': fe_res})

,PooledOLS,RE,FE
Dep. Variable,income_to_cost,income_to_cost,income_to_cost
Estimator,PooledOLS,RandomEffects,PanelOLS
No. Observations,486,486,486
Cov. Est.,Clustered,Clustered,Clustered
R-squared,0.3303,0.1304,0.1687
R-Squared (Within),0.0329,0.1062,0.1687
R-Squared (Between),0.4964,0.3516,-5.2703
R-Squared (Overall),0.3303,0.2647,-4.5603
F-statistic,26.081,7.9322,14.272
P-value (F-stat),0.0000,0.0000,0.0000


## Mundlak simple attempt

In [41]:
import pandas as pd
from linearmodels.panel import RandomEffects
import statsmodels.api as sm

time_varying_vars = [
    "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag",
    "loans_over_assets_lag", "non_interest_income_lag", "gearing_lag"
]

# Mundlak means
df_means = df[time_varying_vars].groupby(level=0).transform('mean')
df_means.columns = [f"{col}_mean" for col in df_means.columns]

X_mundlak = pd.concat([df, df_means], axis=1)

features = time_varying_vars + df_means.columns.tolist() + ["dc_BEC", "dc_NBS", "dc_Bankdata"]
X_m = sm.add_constant(X_mundlak[features])

mundlak_mod = RandomEffects(y, X_m)
mundlak_res = mundlak_mod.fit(cov_type='clustered', cluster_entity=True)

print(mundlak_res.summary)

                        RandomEffects Estimation Summary                        
Dep. Variable:         income_to_cost   R-squared:                        0.2114
Estimator:              RandomEffects   R-squared (Between):              0.5480
No. Observations:                 486   R-squared (Within):               0.1687
Date:                Thu, May 28 2026   R-squared (Overall):              0.3806
Time:                        01:04:18   Log-likelihood                   -34.733
Cov. Estimator:             Clustered                                           
                                        F-statistic:                      8.3982
Entities:                          58   P-value                           0.0000
Avg Obs:                       8.3793   Distribution:                  F(15,470)
Min Obs:                       1.0000                                           
Max Obs:                      10.0000   F-statistic (robust):             20.355
                            

In [42]:
# Mundla + Year effects
# year dummies generation:
year_dummies = pd.get_dummies(df.index.get_level_values(1), drop_first=True).astype(float)
year_dummies.columns = [f"year_{c}" for c in year_dummies.columns]
year_dummies.index = df.index

X_with_years = pd.concat([X_m, year_dummies], axis=1)
mundlak_years_res = RandomEffects(y, X_with_years).fit(cov_type='clustered', cluster_entity=True)

# Wald test
year_cols = year_dummies.columns.tolist()
constraints = [f"{col} = 0" for col in year_cols]
wald_test = mundlak_years_res.wald_test(formula=constraints)

print(f"Wald test stat={wald_test.stat:.4f}, p-value={wald_test.pval:.4f}")
print(mundlak_years_res.summary)

Wald test stat=231.4212, p-value=0.0000
                        RandomEffects Estimation Summary                        
Dep. Variable:         income_to_cost   R-squared:                        0.4493
Estimator:              RandomEffects   R-squared (Between):              0.5280
No. Observations:                 486   R-squared (Within):               0.4456
Date:                Thu, May 28 2026   R-squared (Overall):              0.4732
Time:                        01:04:20   Log-likelihood                    66.906
Cov. Estimator:             Clustered                                           
                                        F-statistic:                      15.674
Entities:                          58   P-value                           0.0000
Avg Obs:                       8.3793   Distribution:                  F(24,461)
Min Obs:                       1.0000                                           
Max Obs:                      10.0000   F-statistic (robust):        

In [43]:
# H2 - pairwise tests
test_bec_nbs = mundlak_years_res.wald_test(formula="dc_BEC - dc_NBS = 0")
test_bec_bd  = mundlak_years_res.wald_test(formula="dc_BEC - dc_Bankdata = 0")
test_nbs_bd  = mundlak_years_res.wald_test(formula="dc_NBS - dc_Bankdata = 0")

print(f"BEC vs NBS:      Stat={test_bec_nbs.stat:.4f}, p-value={test_bec_nbs.pval:.4f}")
print(f"BEC vs Bankdata: Stat={test_bec_bd.stat:.4f}, p-value={test_bec_bd.pval:.4f}")
print(f"NBS vs Bankdata: Stat={test_nbs_bd.stat:.4f}, p-value={test_nbs_bd.pval:.4f}")

joint_test = mundlak_years_res.wald_test(formula=["dc_BEC - dc_NBS = 0", "dc_NBS - dc_Bankdata = 0"])
print(f"\nJoint Test (All equal): Stat={joint_test.stat:.4f}, p-value={joint_test.pval:.4f}")

BEC vs NBS:      Stat=0.1134, p-value=0.7363
BEC vs Bankdata: Stat=0.5346, p-value=0.4647
NBS vs Bankdata: Stat=0.2217, p-value=0.6378

Joint Test (All equal): Stat=0.5983, p-value=0.7414


In [44]:
from statsmodels.stats.diagnostic import het_breuschpagan

bp_test = het_breuschpagan(mundlak_res.resids, X_m)

print(f"Test Breusch-Pagan LM-stat={bp_test[0]:.4f}, p-value={bp_test[1]:.4f}")

Test Breusch-Pagan LM-stat=53.7293, p-value=0.0000


In [45]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# VIF
vif_data = pd.DataFrame()
vif_data["variable"] = X_m.columns
vif_data["VIF"] = [variance_inflation_factor(X_m.values, i) for i in range(X_m.shape[1])]

print("\n--- VIF ---")
print(vif_data.sort_values(by="VIF", ascending=False))


--- VIF ---
                         variable         VIF
0                           const  775.122678
7       log_total_assets_lag_mean   75.105381
1            log_total_assets_lag   73.805026
10     loans_over_assets_lag_mean   15.070219
9   deposits_over_assets_lag_mean   14.044090
3        deposits_over_assets_lag   12.255518
4           loans_over_assets_lag   12.034057
8              tier1_cap_lag_mean    9.993179
2                   tier1_cap_lag    9.190848
14                         dc_NBS    8.671929
13                         dc_BEC    8.052161
12               gearing_lag_mean    7.066285
11   non_interest_income_lag_mean    6.982891
5         non_interest_income_lag    6.008905
6                     gearing_lag    5.536603
15                    dc_Bankdata    4.989741


In [46]:
## Pooled playground

from linearmodels.panel import PanelOLS
import numpy as np

dfp = df_clean.copy()
dfp["post_2019"] = (dfp.index.get_level_values("year") >= 2019).astype(int)
dfp['dc_Bankdata_post2019'] = dfp['dc_Bankdata'] * dfp['post_2019']
dfp['dc_NBS_post2019'] = dfp['dc_NBS'] * dfp['post_2019']
dfp['dc_BEC_post2019'] = dfp['dc_BEC'] * dfp['post_2019']
# dfp['fee_income_growth'] = (
#     np.log1p(dfp['fee_commission_income'])
#     .groupby(level='bank')
#     .diff()
# )
dfp['cti_mean_t'] = (
    dfp
    .groupby(level='year')['income_to_cost']
    .transform('mean')
)
dfp['cti_dev'] = abs(dfp['income_to_cost'] - dfp['cti_mean_t'])
dfp = dfp.replace([np.inf, -np.inf], np.nan).dropna()
yp = dfp["cti_dev"]
Xp = dfp[["dc_BEC", "dc_NBS", "dc_Bankdata", "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag", "non_interest_income_lag", "post_2019", "dc_NBS_post2019", "dc_Bankdata_post2019", "dc_BEC_post2019"]]
Xp = sm.add_constant(Xp)

from linearmodels.panel import PanelOLS

fe_mod = PanelOLS(
    yp,
    Xp,
    entity_effects=True,
    time_effects=True,
    drop_absorbed=True
)

fe_res = fe_mod.fit(cov_type="clustered", cluster_entity=True)

print(fe_res.summary)

                          PanelOLS Estimation Summary                           
Dep. Variable:                cti_dev   R-squared:                        0.0864
Estimator:                   PanelOLS   R-squared (Between):             -0.6319
No. Observations:                1383   R-squared (Within):              -0.0233
Date:                Thu, May 28 2026   R-squared (Overall):             -0.5687
Time:                        01:04:30   Log-likelihood                    104.95
Cov. Estimator:             Clustered                                           
                                        F-statistic:                      15.042
Entities:                          80   P-value                           0.0000
Avg Obs:                       17.288   Distribution:                  F(8,1272)
Min Obs:                       1.0000                                           
Max Obs:                       24.000   F-statistic (robust):             4.9417
                            

/var/folders/7b/yfxzgtr11sg43l79k4r2dwgc0000gn/T/ipykernel_7095/845700996.py:37: AbsorbingEffectWarning: 
Variables have been fully absorbed and have removed from the regression:

dc_BEC, dc_NBS, dc_Bankdata, post_2019

  fe_res = fe_mod.fit(cov_type="clustered", cluster_entity=True)


In [47]:
# DCs should offer different level of automatization, thus influencing the expenses on staff

dfp = df_clean.copy()
y = dfp["admin_exp_over_assets"]
X = dfp[["dc_BEC", "dc_NBS", "dc_Bankdata", "log_total_assets_lag", "tier1_cap_lag", "deposits_over_assets_lag", "loans_over_assets_lag"]]

X = sm.add_constant(X)
pooled_mod = PooledOLS(y, X)
pooled_res = pooled_mod.fit(cov_type="clustered", cluster_entity=True)

print(pooled_res.summary)


                            PooledOLS Estimation Summary                           
Dep. Variable:     admin_exp_over_assets   R-squared:                        0.0484
Estimator:                     PooledOLS   R-squared (Between):              0.1920
No. Observations:                   1383   R-squared (Within):              -0.0039
Date:                   Thu, May 28 2026   R-squared (Overall):              0.0484
Time:                           01:04:38   Log-likelihood                    1409.0
Cov. Estimator:                Clustered                                           
                                           F-statistic:                      9.9907
Entities:                             80   P-value                           0.0000
Avg Obs:                          17.288   Distribution:                  F(7,1375)
Min Obs:                          1.0000                                           
Max Obs:                          24.000   F-statistic (robust):            